# -*- coding: utf-8 -*-
"""Token

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1soWfoR1PcxNOwlZMJ-_OvIlC7aR6Cgoi
"""

# import
from google.colab import files
import pandas as pd
import numpy as np

# function definitions
def upload_and_load_dataframe(message):
    print(message)
    upload = files.upload()
    file = next(iter(upload))
    df = pd.read_excel(file)
    return file, df

def convert_to_xlsx(df):
  df['Instant debit amount'].fillna('', inplace=True)
  columns_to_convert = ['Card_Number', 'Instant debit amount', 'Payment gateway response code']
  df[columns_to_convert] = df[columns_to_convert].astype(str)

  return df

def initalize_tokenfile_format():
  tokenfile_format = {
      'External Pledge Reference Id' : [],
      'First_Name' : [],
      'Last_Name' : [],
      'Card_Number' : [],
      'Expiry Date' : [],
      'CardHolder Name' : [],
      'Donation Date' : [],
      'Donation Amount' : [],
      'Email' : [],
      'Mobile_Phone' : [],
      'Location' : [],
      'Office Name' : [],
      'Fundraiser full name' : [],
      'Team Leader' : [],
      'Campaign Manager' : [],
      'Supporter Payment method' : [],
      'Credit Card Type' : [],
      'Payment Type' : [],
      'Instant debit amount' : [],
      'Successful instant debit' : [],
      'Payment gateway message' : [],
      'Payment gateway response code' : [],
      'Reconciliation ID' : [],
      }
  return pd.DataFrame(tokenfile_format)

def copy_data(df3, df2):
  df3['External Pledge Reference Id'] = df2['Pledge ID']
  df3['First_Name'] = df2['First Name']
  df3['Last_Name'] = df2['Last Name']
  df3['Card_Number'] = df2['PAN 16/15 digits'].astype(str)
  df3['Expiry Date'] = df2['Expiry Date MM/YY format']
  df3['CardHolder Name'] = df2['CardHolder Name']
  df3['Donation Date'] = '12/01/2023'
  df3['Donation Amount'] = 60
  df3['Email'] = 'joharisuleiman87@gmail.com'
  df3['Mobile_Phone'] = '017-3316286'
  df3['Location'] = 'Mydin Subang Jaya'
  df3['Office Name'] = 'KL Office 1'
  df3['Fundraiser full name'] = 'Malliga A/P Munusamy'
  df3['Team Leader'] = 'Malliga A/P Munusamy'
  df3['Campaign Manager'] = 'Mohamad Syukran Bin Anuar'
  df3['Supporter Payment method'] = 'Credit Card'
  df3['Credit Card Type'] = 'VS'
  df3['Payment Type'] = 'VS'
  df3['Instant debit amount'] = ''
  df3['Successful instant debit'] = 'No'
  df3['Payment gateway message'] = 'Insufficient funds in the account'
  df3['Payment gateway response code'] = '204'
  df3['Reconciliation ID'] = ''

  return df3

def change_card_type(df3):
  conditions = [
      df3['Card_Number'].str.startswith('4'),
      df3['Card_Number'].str.startswith('5'),
      df3['Card_Number'].str.startswith('3')
  ]
  choices = ['VS', 'MC', 'AX']

  df3['Credit Card Type'] = np.select(conditions, choices, default = '')
  df3['Payment Type'] = df3['Credit Card Type']

  return df3

def export_to_excel(df,output_filename):
  df.to_excel(output_filename, index=False)
  files.download(output_filename)

# main function
def main():
  user_input = int(input('Choose what to do:\n 1.Convert File\n 2.New Token File\n 3.Both \n\n'))

  if user_input == 1:
    #Upload
    convert_file, df = upload_and_load_dataframe('Upload file to convert to .xlsx')

    #print
    print('Converting file ...')

    #apply changes
    converted_df = convert_to_xlsx(df)

    #rename and download
    converted_filename = convert_file.split('.')[0] + '.xlsx'
    export_to_excel(converted_df, converted_filename)

  elif user_input == 2:
    #Upload
    token_file, df2 = upload_and_load_dataframe('Upload New Token file')

    #print
    print('Transforming New Token File ...')

    #apply changes
    df3 = initalize_tokenfile_format()
    df3 = copy_data(df3, df2)
    df3 = change_card_type(df3)

    #rename and download
    to_token_filename = f'{token_file.split(".")[0]} - To Token.xlsx'
    export_to_excel(df3, to_token_filename)

  else:
    #Upload
    convert_file, df = upload_and_load_dataframe('Upload file to convert to .xlsx')
    token_file, df2 = upload_and_load_dataframe('Upload New Token file')


    #print
    print('Converting and Transforming file ...')

    #apply changes
    converted_df = convert_to_xlsx(df)
    df3 = initalize_tokenfile_format()
    df3 = copy_data(df3, df2)
    df3 = change_card_type(df3)

    #rename and download
    converted_filename = convert_file.split('.')[0] + '.xlsx'
    to_token_filename = f'{token_file.split(".")[0]} - To Token.xlsx'
    export_to_excel(converted_df, converted_filename)
    export_to_excel(df3, to_token_filename)

if __name__ == "__main__":
  main()